c_compiler:
  - gcc                        # [linux]
  - vs2019                     # [win]
c_stdlib:
  - sysroot                    # [linux]
  - vs                         # [win]
cxx_compiler:
  - gxx                        # [linux]
  - vs2019                     # [win]
  # - vs2022                     # [win]
cuda_compiler:
  - cuda-nvcc
fortran_compiler:
  - gfortran                   # [linux]
  - intel-fortran              # [win]

c_compiler_version:        # [linux]
  - 11.2.0                 # [linux]
c_stdlib_version:
  - 2.28                   # [linux]
  - 2019.11                # [win]
  # - 2022.14                # [win]
cxx_compiler_version:      # [linux]
  - 11.2.0                 # [linux]
cuda_compiler_version:
  - 12.8
fortran_compiler_version:
  - 2022.1.0                     # [win]
  - 11.2.0                       # [linux]
