######### Configure these for each git tag release #########
git_tag:
  - "v12.8.0"
bindings_version:
  - "12.8.0"
core_version:
  - "0.1.1"
build_bindings:
  - True
build_core:
  - False

c_compiler:
  - gcc                        # [linux]
  - vs2019                     # [win]
c_stdlib:
  - sysroot                    # [linux]
  - vs                         # [win]
cxx_compiler:
  - gxx                        # [linux]
  - vs2019                     # [win]
cuda_compiler:
  - cuda-nvcc
fortran_compiler:
  - gfortran                   # [linux]
  - intel-fortran              # [win]

c_compiler_version:        # [linux]
  - 11.2.0                 # [linux]
c_stdlib_version:
  - 2.28                   # [linux]
  - 2019.11                # [win]
cxx_compiler_version:      # [linux]
  - 11.2.0                 # [linux]
cuda_compiler_version:
  - 12.8
fortran_compiler_version:
  - 2022.1.0                     # [win]
  - 11.2.0                       # [linux]
