{% set name = "cuda-python" %}
{% set number = 0 %}

# cuda-python version is in sync with cuda-bindings version
{% set version = "12.8.0" %}
# cuda-python keeps different versioning scheme for the included modules
{% set core_version = "0.1.1" %}

# Git tag should be in sync with cuda-python version.
# However, there might be exceptions for the included cuda-python modules.
# Ex: "cuda-core-v*" tags on the upstream repository.
{% set git_tag = "v" ~ version %}

# Enable building of the modules included in the upstream repository
{% set build_bindings = True %}
{% set build_core = True %}

{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win64]
{% set subdir = "" %}
{% set subdir = os.sep.join(["", "targets", target_name]) %}  # [linux64 or aarch64]
{% set subdir = os.sep.join(["", "Library"]) %}  # [win64]

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuda-python/releases/download/{{ git_tag }}/cuda-python-{{ git_tag }}.tar.gz
  sha256: 6cc8db1e65a1f995e289b64f9b9bff4362321d36ecf9b54eb192d0781475fbca

build:
  number: {{ number }}
  skip: true  # [py < 310 or osx]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    - python
    - pip
    - setuptools
    - cython

outputs:
  # cuda-python is a metapackage
  - name: {{ name }}
    version: {{ version }}
    # Keep scripts under outputs section to ensure building the modules/packages provided by cuda-python
    script: build_output.sh   # [linux]
    script: build_output.bat  # [win]
    build:
      number: {{ number }}
      ignore_prefix_files:
        - '**/*.c'
        - '**/*.cpp'
        - '**/*.so.c'
    requirements:
      host:
        - python
        - pip
        - setuptools
      run:
        - python
        - {{ pin_subpackage('cuda-bindings', exact=True) }}
        - {{ pin_compatible('cuda-version', min_pin='x.x', max_pin='x.x') }}
    test:
      requires:
        - python
        - {{ pin_subpackage('cuda-bindings', exact=True) }}
      imports:
        - cuda.bindings
        - cuda.bindings.driver
        - cuda.bindings.runtime
        - cuda.bindings.nvrtc
        - cuda.bindings.nvjitlink
      commands:
        - python -c "import importlib.metadata; importlib.metadata.version('cuda-python')"
    about:
      home: https://nvidia.github.io/cuda-python/
      license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
      license_file: cuda_python/LICENSE
      license_url: https://github.com/NVIDIA/cuda-python/blob/main/cuda_python/LICENSE
      summary: CUDA Python
      description: |
        CUDA Python is the home for accessing NVIDIA's CUDA platform from Python
      doc_url: https://nvidia.github.io/cuda-python/
      dev_url: https://github.com/NVIDIA/cuda-python

  - name: cuda-bindings
    version: {{ version }}
    # Keep scripts under outputs section to ensure building the modules/packages provided by cuda-python
    script: build_output.sh   # [linux]
    script: build_output.bat  # [win]
    build:
      number: {{ number }}
      skip: {{not build_bindings}}
      script_env:
        # Ensure that CUDA includes can be found by the host compiler
        - CUDA_HOME={{ PREFIX ~ subdir ~ os.pathsep ~ BUILD_PREFIX ~ subdir }}
      run_exports:
        - {{ pin_subpackage('cuda-bindings', min_pin='x.x', max_pin='x.x') }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
        # The run-exports from these dev packages are too tight, so we ignore them.
        # The cuda-python package supports CUDA Enhanced Compatibility through its
        # use of dlopen, so it is compatible with other CUDA minor versions.
        - cuda-cudart-dev
        - cuda-nvrtc-dev
      ignore_prefix_files:
        - '**/*.c'
        - '**/*.cpp'
        - '**/*.so.c'
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ pin_compatible('cuda-version', min_pin='x.x', max_pin='x.x') }}
      host:
        - python
        - pip
        - setuptools
        - cython
        - pyclibrary 0.3.0
        - {{ pin_compatible('cuda-version', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cuda-cudart-dev', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cuda-cudart', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cuda-nvrtc-dev', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cuda-nvrtc', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cuda-profiler-api', min_pin='x.x', max_pin='x.x') }}
      run:
        - python
        - {{ pin_compatible('cuda-version', min_pin='x.x', max_pin='x.x') }}
        # cuda-python requires cuda-nvrtc from the same major version. We ignored
        # run-exports of cuda-nvrtc-dev and instead allow a looser pinning here.
        - {{ pin_compatible('cuda-nvrtc', min_pin='x', max_pin='x') }}
        - libnvjitlink >=12.3
        - pywin32  # [win64]
      run_constrained:
        # cuda-cudart is not a hard dependency because cuda-python re-implements
        # cudart. This package is optionally dlopen'd for getting the local cudart
        # version with cuda.cudart.getLocalRuntimeVersion(). We ignored run-exports
        # of cuda-cudart-dev and instead allow a looser pinning here.
        - {{ pin_compatible('cuda-cudart', min_pin='x', max_pin='x') }}
        # cuda-bindings and cuda-python versions should be kept in sync
        - {{ pin_subpackage('cuda-python', max_pin='x.x') }}
    test:
      requires:
        - python
        - setuptools
        - cython
        # Required due to 'cythonize' in the test commands
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - cuda-nvrtc-dev
        - cuda-profiler-api
      files:
        - test_cimport.pyx
      commands:
        - export C_INCLUDE_PATH="$CONDA_PREFIX/{{ subdir }}/include"  # [linux]
        - set "CL=%CL% /I%CONDA_PREFIX%\{{ subdir }}\include"         # [win]
        - cythonize -i -3 test_cimport.pyx
        - python -c "import test_cimport; test_cimport.test()"
        - python -c "import cuda.bindings; print(cuda.bindings.__version__)"
      imports:
        - cuda
        - cuda.cuda
        - cuda.cudart
    about:
      home: https://nvidia.github.io/cuda-python/cuda-bindings
      license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
      license_file: cuda_bindings/LICENSE
      license_url: https://github.com/NVIDIA/cuda-python/blob/main/cuda_bindings/LICENSE
      summary: Low-level Python bindings for CUDA
      description: |
        cuda.bindings is a standard set of low-level interfaces,
        providing full coverage of and access to the CUDA host APIs from Python.
      doc_url: https://nvidia.github.io/cuda-python/cuda-bindings
      dev_url: https://github.com/NVIDIA/cuda-python

  - name: cuda-core
    version: {{ core_version }}
    # Keep scripts under outputs section to ensure building the modules/packages provided by cuda-python
    script: build_output.sh   # [linux]
    script: build_output.bat  # [win]
    build:
      number: {{ number }}
      skip: {{not build_core}}
      run_exports:
        - {{ pin_subpackage('cuda-core', min_pin='x.x', max_pin='x.x') }}
      ignore_prefix_files:
        - '**/*.c'
        - '**/*.cpp'
        - '**/*.so.c'
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
      host:
        - python
        - pip
        - setuptools
        - cython
        - {{ pin_subpackage('cuda-bindings', exact=True) }}
      run:
        - python
        - numpy
        - {{ pin_compatible('cuda-version', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_subpackage('cuda-bindings', exact=True) }}
    test:
      requires:
        - python
      commands:
        - python -c "from cuda.core.experimental import Device"
        - python -c "from cuda.core.experimental import utils"
      imports:
        - cuda.core.experimental
    about:
      home: https://nvidia.github.io/cuda-python/cuda-core
      license: Apache-2.0
      license_file: cuda_core/LICENSE
      license_url: https://github.com/NVIDIA/cuda-python/blob/main/cuda_core/LICENSE
      summary: Pythonic access to CUDA core functionality (experimental)
      description: |
        cuda.core offers idiomatic, Pythonic access to CUDA Runtime and other functionalities.
      doc_url: https://nvidia.github.io/cuda-python/cuda-core
      dev_url: https://github.com/NVIDIA/cuda-python

about:
  home: https://nvidia.github.io/cuda-python/
  license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
  license_url: https://github.com/NVIDIA/cuda-python/blob/main/LICENSE.md
  summary: CUDA Python
  description: |
    CUDA Python is the home for accessing NVIDIA's CUDA platform from Python.
  doc_url: https://nvidia.github.io/cuda-python/
  dev_url: https://github.com/NVIDIA/cuda-python

extra:
  feedstock-name: cuda-python
  recipe-maintainers:
    - bdice
    - jakirkham
    - leofang
    - m3vaz
    - mmccarty
    - vyasr
    - vzhurba01
