{% set name = 'cuda-python' %}
{% set number = 0 %}
{% set version = '12.9.4' %}

# Important note:
# We don't have CUDA Toolkit 12.9 in conda main channel at this time.
# Therefore, "cuda_compiler_version == short_version" checks are removed temporarily
# We could remove them completely after CUDA Toolkit 13 release

{% set short_version = version.split('.')[:2] | join('.') %}
{% set cuda_major_version = (cuda_compiler_version|string).split('.')[0] %}
# {% set cuda_minor_version = (cuda_compiler_version|string).split('.')[1] %}
{% set target_name = 'x86_64-linux' %}  # [linux]
{% set target_name = 'sbsa-linux' %}  # [aarch64]
{% set target_name = 'x64' %}  # [win]
{% set subdir = '' %}
{% set subdir = os.sep.join(['', 'targets', target_name]) %}  # [linux or aarch64]
{% set subdir = os.sep.join(['', 'Library']) %}  # [win]

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: e08eac307f3f17bf163ffc9d1a493bb93c10e94948a4117b7e33d76452ae0b79

build:
  number: {{ number }}
  skip: true  # [py <310 or osx]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    - python

outputs:
  # cuda-python is a metapackage as of v12.8
  - name: {{ name }}
    version: {{ version }}
    # Keep scripts under outputs section to ensure building the modules/packages provided by cuda-python
    script: build_output.sh   # [linux]
    script: build_output.bat  # [win]
    build:
      number: {{ number }}
      #{% if not (cuda_compiler_version == short_version) %}
      #skip: true
      #{% endif %}
    requirements:
      build:
        - cuda-version {{ cuda_major_version }}.*
      host:
        - python
        - pip
        - setuptools
        - cuda-version {{ cuda_major_version }}.*
      run:
        - python
        # Keep cuda-python pin compatible with cuda-bindings major.minor version.
        # This is to make sure that installing cuda-python x.y would always install cuda-bindings x.y
        # CUDA minor version compatibility should allow cuda-bindings v12.y work with any CUDA Toolkit v12.y
        # Please refer to the following documents for details:
        #   * https://nvidia.github.io/cuda-python/cuda-bindings/latest/support.html
        #   * https://docs.nvidia.com/deploy/cuda-compatibility/minor-version-compatibility.html
        - {{ pin_subpackage('cuda-bindings', min_pin='x.x', max_pin='x.x') }}
        # Keep cuda-python pin compatible with cuda-version major only.
        # Please refer to the following documents for details:
        #   * https://nvidia.github.io/cuda-python/cuda-bindings/latest/support.html
        #   * https://docs.nvidia.com/deploy/cuda-compatibility/minor-version-compatibility.html
        - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}
    test:
      requires:
        - pip
      imports:
        - cuda.bindings
        - cuda.bindings.driver
        - cuda.bindings.runtime
        - cuda.bindings.nvrtc
        - cuda.bindings.nvjitlink
        - cuda.bindings.cufile  # [linux]
      commands:
        - pip check
        - python -c "import importlib.metadata; importlib.metadata.version('cuda-python')"
    about:
      home: https://nvidia.github.io/cuda-python
      license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
      license_file: cuda_python/LICENSE
      license_url: https://github.com/NVIDIA/cuda-python/blob/main/cuda_python/LICENSE
      summary: CUDA Python
      description: |
        CUDA Python is the home for accessing NVIDIA's CUDA platform from Python
      doc_url: https://nvidia.github.io/cuda-python
      dev_url: https://github.com/NVIDIA/cuda-python

  - name: cuda-bindings
    version: {{ version }}
    # Keep scripts under outputs section to ensure building the modules/packages provided by cuda-python
    script: build_output.sh   # [linux]
    script: build_output.bat  # [win]
    build:
      number: {{ number }}
      #{% if not (cuda_compiler_version == short_version) %}
      #skip: true
      #{% endif %}
      script_env:
        # Ensure that CUDA includes can be found by the host compiler
        - CUDA_HOME={{ PREFIX ~ subdir }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
        # The run-exports from these dev packages are too tight, so we ignore them.
        # The cuda-python package supports CUDA Enhanced Compatibility through its
        # use of dlopen, so it is compatible with other CUDA minor versions.
        - cuda-nvcc-impl
        - cuda-cudart-dev
        - cuda-cudart-static
        - cuda-nvrtc-dev
        - libcufile-dev  # [linux]
      # Do not include cython-generated source files
      ignore_prefix_files:
        - '**/*.c'
        - '**/*.cpp'
        - '**/*.so.c'
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - cuda-version {{ cuda_major_version }}.*
      host:
        - python
        - pip
        - setuptools
        - cython >=3.1,<3.2
        - pyclibrary
        - cuda-version {{ cuda_major_version }}.*
        - cuda-crt-dev_{{ target_platform }}
        - cuda-cudart-dev
        - cuda-cudart-static
        - cuda-cudart
        - cuda-nvcc-impl
        - cuda-nvrtc
        - cuda-nvrtc-dev
        - cuda-profiler-api
        - libcufile  # [linux]
        - libcufile-dev  # [linux]
      run:
        - python
        # Keep cuda-bindings pin compatible with cuda-version major only.
        # Please refer to the following documents for details:
        #   * https://nvidia.github.io/cuda-python/cuda-bindings/latest/support.html
        #   * https://docs.nvidia.com/deploy/cuda-compatibility/minor-version-compatibility.html
        - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}
        # cuda-python requires cuda-nvrtc from the same major version. We ignored
        # run-exports of cuda-nvrtc-dev and instead allow a looser pinning here.
        # Same for cuda-nvcc-impl.
        - {{ pin_compatible('cuda-nvrtc', min_pin='x', max_pin='x') }}
        - {{ pin_compatible('cuda-nvcc-impl', min_pin='x', max_pin='x') }}
        - {{ pin_compatible('libcufile', min_pin='x', max_pin='x') }}  # [linux and cufile_supported]
        - libnvjitlink >=12.3,<13
        - numpy  # [linux]
        - cuda-pathfinder >=1.1.0,<2
      run_constrained:
        # cuda-cudart is not a hard dependency because cuda-python re-implements
        # cudart. This package is optionally dlopen'd for getting the local cudart
        # version with cuda.cudart.getLocalRuntimeVersion(). We ignored run-exports
        # of cuda-cudart-dev and instead allow a looser pinning here.
        - {{ pin_compatible('cuda-cudart', min_pin='x', max_pin='x') }}
    test:
      requires:
        - pip
        - cython >=3.1,<3.2
        # The following are required for 'cythonize' in the test commands
        - setuptools
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - cuda-nvrtc-dev
        - cuda-profiler-api
      files:
        - test_cimport.pyx
      imports:
        - cuda
        - cuda.cuda
        - cuda.cudart
        - cuda.bindings
        - cuda.bindings.driver
        - cuda.bindings.runtime
        - cuda.bindings.cufile  # [linux]
        - cuda.bindings.nvrtc
        - cuda.bindings.nvjitlink
        - cuda.bindings.nvvm
      commands:
        - pip check
        - export C_INCLUDE_PATH="$CONDA_PREFIX/{{ subdir }}/include"  # [linux]
        - set "CL=%CL% /I%CONDA_PREFIX%\{{ subdir }}\include"         # [win]
        - cythonize -i -3 test_cimport.pyx
        - python -c "import test_cimport; test_cimport.test()"
        - python -c "import cuda.bindings; print(cuda.bindings.__version__)"

    about:
      home: https://nvidia.github.io/cuda-python/cuda-bindings
      license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
      license_file: cuda_bindings/LICENSE
      license_url: https://github.com/NVIDIA/cuda-python/blob/main/cuda_bindings/LICENSE
      summary: Low-level Python bindings for CUDA
      description: |
        cuda.bindings is a standard set of low-level interfaces,
        providing full coverage of and access to the CUDA host APIs from Python.
      doc_url: https://nvidia.github.io/cuda-python/cuda-bindings
      dev_url: https://github.com/NVIDIA/cuda-python

about:
  home: https://nvidia.github.io/cuda-python
  license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
  license_url: https://github.com/NVIDIA/cuda-python/blob/main/LICENSE.md
  summary: CUDA Python
  description: |
    CUDA Python is the home for accessing NVIDIA's CUDA platform from Python.
  doc_url: https://nvidia.github.io/cuda-python
  dev_url: https://github.com/NVIDIA/cuda-python

extra:
  feedstock-name: cuda-python
  recipe-maintainers:
    - bdice
    - jakirkham
    - leofang
    - m3vaz
    - mmccarty
    - vyasr
    - vzhurba01
